export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';
export const CHANGE_REGISTER_FORM = 'CHANGE_REGISTER_FORM';
export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';

export const CHANGE_USERS_NEW_PROJECT_FORM = 'CHANGE_USERS_NEW_PROJECT_FORM';
export const CHANGE_ID_NEW_PROJECT_FORM = 'CHANGE_ID_NEW_PROJECT_FORM';
export const CHANGE_PROJECT_SAVED = 'CHANGE_PROJECT_SAVED';
export const CHANGE_RESPONSIBLE_USER = 'CHANGE_RESPONSIBLE_USER';
export const CHANGE_PROJECT_WILL_CREATE = 'CHANGE_PROJECT_WILL_CREATE';
export const CHANGE_FIND_TEAM_BUGDET_ERROR = 'CHANGE_FIND_TEAM_BUGDET_ERROR';
export const SET_ACCEPT_SUGGESTION_STATUS = 'SET_ACCEPT_SUGGESTION_STATUS';

export const SET_PROJECT_CREATED_STATUS = 'SET_PROJECT_CREATED_STATUS';
export const RESET_PROJECT_WILL_CREATE = 'RESET_PROJECT_WILL_CREATE';

export const CHANGE_CREATE_MODE = 'CHANGE_CREATE_MODE';
export const CHANGE_VISIBLE_CREATE_MODE_MODAL = 'CHANGE_VISIBLE_CREATE_MODE_MODAL';