export const CHANGE_VISIBLE_STATE = 'CHANGE_VISIBLE_STATE';

export const CHANGE_VALUE_STATE = 'CHANGE_VALUE_STATE';

export const CHANGE_FP_TABLE_ARRAY = 'CHANGE_FP_TABLE_ARRAY';

export const SET_FUNCTION_POINT_DONE = 'SET_FUNCTION_POINT_DONE';