

export const CHANGE_EAF= 'CHANGE_EAF';
export const CHANGE_SCALE_FACTORS = 'CHANGE_SCALE_FACTORS';
export const CHANGE_FUNCTION_POINT = 'CHANGE_FUNCTION_POINT';
export const CHANGE_KLOC = 'CHANGE_KLOC';
export const CHANGE_ESTIMATED_RESULT = 'CHANGE_ESTIMATED_RESULT';
export const CHANGE_BRUTEFORCE_STAFFS = 'CHANGE_BRUTEFORCE_STAFFS';
export const CHANGE_STAFF_REQUIREMENTS = 'CHANGE_STAFF_REQUIREMENTS';
export const RESET_ESTIMATED_RESULT = 'RESET_ESTIMATED_RESULT';
export const CHANGE_ESTIMATE_MODE = 'CHANGE_ESTIMATE_MODE';
export const VIEW_ESTIMATE_MODE = 'VIEW_ESTIMATE_MODE';
export const CHANGE_PRE_PICK_STAFFS = 'CHANGE_PRE_PICK_STAFFS';
// export const GET_SUITABLE_STAFF = 'GET_SUITABLE_STAFF';
// export const CACULATE_EAF = 'CACULATE_EAF';